MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"
    STEM_OUT_CHANNELS: 64 
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]
DATASETS:
  TRAIN: ("pascal_voc_train_sem_seg",)
  TEST: ("pascal_voc_test_sem_seg",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  MAX_ITER: 20000
  WARMUP_FACTOR: 1.0 
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW" 
  MOMENTUM: 0.9
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CHECKPOINT_PERIOD: 2000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: [256, 384, 512, 640, 768]
  # MIN_SIZE_TRAIN [0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 1024
  MAX_SIZE_TEST: 1024
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 512)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 512
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
TEST:
  EVAL_PERIOD: 1000
  AUG:
    ENABLED: True
    MIN_SIZES: [256, 384, 512, 640, 768, 896]
    # MIN_SIZES: 0.5, 0.75, 1.0, 1.25, 1.5, 1.75 -> [256.0, 384.0, 512.0, 640.0, 768.0, 896.0]
    MAX_SIZE: 1024
    FLIP: True
DATALOADER:
  NUM_WORKERS: 4
VERSION: 2