_BASE_: maskformer_R50_bs16_160k.yaml
DATASETS:
  TRAIN: ("ade20k_5052_sem_seg_train",)
  TEST: ("ade20k_sem_seg_val",)
  SEMI_SPLIT_RATIO: 1.0
MODEL:
  MASK_FORMER:
    FIXED_MATCHING: True
    NUM_OBJECT_QUERIES: 150
SOLVER:
  UNLABELED_RATIO: 0.0
  IMS_PER_BATCH: 16
  MAX_ITER: 160000

    
